### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kireerik** [wilsonzlin/minify-js#22]
```
import {minify} from '@minify-js/node'
        ^^^^^^
SyntaxError: The requested module '@minify-js/node' does not provide an export named 'minify'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24) {
  __stack: [ CallSite {}, CallSite {}, CallSite {} ]
}
```

Importing it properly (`import minifyJs from '@minify-js/node'`) I am getting the following error:
```
minifyJs.minify(Buffer.from(result, 'utf-8'))
              ^

TypeError: failed to downcast any to string
```

**Comment by perrin4869** [comment]
I ran into the same problem.
To solve the top issue, the entry point of the module would just need to be changed from

```
module.exports = require("./index.node");
```

to

```
module.exports.minify = require("./index.node").minify;
```

The second problem I got no clue, seems a problem with the rust integration 😅

**Comment by Black-Platypus** [comment]
Second problem is because the signature definition is `minify(topLevelType: "global" | "module", src: Buffer)`
So you should change the above to `minifyJs.minify("global", Buffer.from(result, 'utf-8'))` if you're working within global scope, or `minifyJs.minify("module", Buffer.from(result, 'utf-8'))` if you're working with a module.

**Comment by kireerik** [comment]
Thank you @Black-Platypus!

This was definitely an issue and this is missing from the readme here (https://github.com/wilsonzlin/minify-js/blob/77dae36c6e0a0f068ffd5c55ccc57c207c8cc017/README.md?plain=1#L80).

Now I am getting the following error:
```
thread '<unnamed>' panicked at rust\src\minify\pass1.rs:288:81:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
file:///.../module/loader/file/action/minify/script.js:6
        return minifyJs.minify('global', Buffer.from(result, 'utf-8'))
                        ^

Error: internal error in Neon module: called `Option::unwrap()` on a `None` value
    at default (file:///.../module/loader/file/action/minify/script.js:6:18)
    at file:///.../source/index/main.js.js:57:25
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:485:26) {
  __stack: [ CallSite {}, CallSite {}, CallSite {}, CallSite {} ]
}

Node.js v22.4.1
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

This is the minifier script (https://github.com/kireerik/refo/blob/ea8f864790aa340275c9593bbcef84a1aa6a1fe3/module/loader/file/action/minify/script.js) where I am attempting to use it instead of the currently used library ([UglifyJS](https://github.com/mishoo/UglifyJS)).

**Comment by Black-Platypus** [comment]
@kireerik Yes, I ran into the exact same issues you're having 😅 
I don't know why it's pointing to line 288 in "pass1.rs", that's just a `};` as far as I can see.
The issue might be that the minifier gets stumped by an empty body of a block of some kind (nothing actionable between an opening curly bracket and a closing curly bracket) and just kills itself because it's so embarrassed; I've traced this error back to not being able to cope with an empty if/else block in "advanced_if.rs".
Since yours is in "pass1.rs", it may be a different kind of block, like
```
function test(){
	// console.log("Everything here is commented out");
	// whereThereUsedToBeCode();
	// console.log("So this block is functionally empty");
}
```
However, I haven't been able to find out what kind of code throws this error in "pass1.rs"; it just sounds like it's complaining about an empty block.
If it's feasible, or just to test things, see if you can eliminate the surrounding things (in this example, comment out the rest, too) or put something in the otherwise empty body.
```
// function test(){
	// console.log("Everything here is commented out");
	// whereThereUsedToBeCode();
	// console.log("So this block is functionally empty");
// }
```

Not that that would be all too helpful in the real world, but I can't write rust, I couldn't even decipher what I was looking at half of the time🥴, so we're left waiting for @wilsonzlin's return.
In the mean time, it would be nice to narrow down the bugs.
